package com.application.admnistration.entity;

public enum AvailableCoursesAtUnilago {
    // Computer Science
    DATA_STRUCTURES,
    ALGORITHMS,
    OPERATING_SYSTEMS,
    DATABASE_SYSTEMS,
    SOFTWARE_ENGINEERING,
    COMPUTER_NETWORKS,
    ARTIFICIAL_INTELLIGENCE,
    MACHINE_LEARNING,

    // Engineering
    CALCULUS_I,
    CALCULUS_II,
    LINEAR_ALGEBRA,
    PHYSICS_I,
    PHYSICS_II,
    THERMODYNAMICS,
    CIRCUIT_ANALYSIS,

    // Business
    MICROECONOMICS,
    MACROECONOMICS,
    FINANCIAL_ACCOUNTING,
    CORPORATE_FINANCE,
    MARKETING_PRINCIPLES,
    BUSINESS_STRATEGY,

    // Law
    CONSTITUTIONAL_LAW,
    CIVIL_LAW,
    CRIMINAL_LAW,
    INTERNATIONAL_LAW,

    // Medicine
    HUMAN_ANATOMY,
    PHYSIOLOGY,
    PATHOLOGY,
    PHARMACOLOGY,
    CLINICAL_MEDICINE
}
